In [36]:
import pandas as pd
import numpy as np
import torch
import sklearn.model_selection as skms
import os
import sklearn as skl

In [ ]:
path = "/home/alexb/roscoff_neonat/TensorFormatFolds/bipolar_18/"
folds = os.listdir(path)

In [42]:
train = []
test = []
for i in range(5):
    test.append(torch.load(path + "test_fold_" + str(i) + ".pt"))
    train.append(torch.load(path + "train_fold_" + str(i) + ".pt"))

In [51]:
print("Linear SVM")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.svm.LinearSVC()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

Linear SVM
Fold: 0
train score:1.0
test score:0.275
Fold: 1
train score:1.0
test score:0.2833333333333333
Fold: 2
train score:0.9972222222222222
test score:0.20833333333333334
Fold: 3
train score:0.9972222222222222
test score:0.5416666666666666
Fold: 4
train score:1.0
test score:0.525


In [44]:
print("Decision Tree")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.tree.DecisionTreeClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

Decision Tree
Fold: 0
train score:1.0
test score:0.2
Fold: 1
train score:1.0
test score:0.38333333333333336
Fold: 2
train score:1.0
test score:0.3
Fold: 3
train score:1.0
test score:0.30833333333333335
Fold: 4
train score:1.0
test score:0.325


In [45]:
print("Extra Tree")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.tree.ExtraTreeClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

Decision Tree
Fold: 0
train score:1.0
test score:0.3
Fold: 1
train score:1.0
test score:0.2916666666666667
Fold: 2
train score:1.0
test score:0.375
Fold: 3
train score:1.0
test score:0.4083333333333333
Fold: 4
train score:1.0
test score:0.425


In [48]:
print("NN")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.neural_network.MLPClassifier(hidden_layer_sizes = (100,50,25,20),max_iter=10000)
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

NN
Fold: 0
train score:1.0
test score:0.325
Fold: 1
train score:1.0
test score:0.36666666666666664
Fold: 2
train score:1.0
test score:0.375
Fold: 3
train score:1.0
test score:0.375
Fold: 4
train score:1.0
test score:0.4


In [50]:
print("ADA Boost")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.ensemble.AdaBoostClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

ADA Boost
Fold: 0
train score:0.675
test score:0.25
Fold: 1
train score:0.7805555555555556
test score:0.425
Fold: 2
train score:0.6944444444444444
test score:0.36666666666666664
Fold: 3
train score:0.6611111111111111
test score:0.3
Fold: 4
train score:0.6454545454545455
test score:0.35


In [ ]:

print("GB")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.ensemble.GradientBoostingClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

GB
Fold: 0
train score:1.0
test score:0.325
Fold: 1
train score:1.0
test score:0.30833333333333335
Fold: 2
train score:1.0
test score:0.38333333333333336
Fold: 3
train score:1.0
test score:0.38333333333333336
Fold: 4
train score:1.0
test score:0.35


In [53]:
print("RF")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.ensemble.RandomForestClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

GB
Fold: 0
train score:1.0
test score:0.325
Fold: 1
train score:1.0
test score:0.325
Fold: 2
train score:1.0
test score:0.38333333333333336
Fold: 3
train score:1.0
test score:0.36666666666666664
Fold: 4
train score:1.0
test score:0.45


In [54]:
print("Kernal Ridge")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.kernel_ridge.KernelRidge()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))

Kernal Ridge
Fold: 0
train score:0.8883143663406372
test score:0.27331072092056274
Fold: 1
train score:0.9031265377998352
test score:0.5017210245132446
Fold: 2
train score:0.872464120388031
test score:0.33599913120269775
Fold: 3
train score:0.8735307455062866
test score:0.4277716279029846
Fold: 4
train score:0.8842914700508118
test score:0.4008445143699646


In [59]:

print("Ridge")
for i in range(5):
    x_train = train[i][0]
    y_train = train[i][1]
    x_test = test[i][0]
    y_test = test[i][1]
    
    svmLinear = skl.linear_model.RidgeClassifier()
    svmLinear.fit(x_train, y_train.ravel())
    print("Fold: " + str(i))
    print("train score:" + str(svmLinear.score(x_train, y_train)))
    print("test score:" +str(svmLinear.score(x_test, y_test)))
    p = svmLinear.predict(x_test)
    print(skl.metrics.confusion_matrix(y_test, p))

Ridge
Fold: 0
train score:0.98
test score:0.3
[[13  4  3  0]
 [ 6  2  8  4]
 [ 5 11  2  2]
 [ 1  1 11  7]]
Fold: 1
train score:0.9833333333333333
test score:0.39166666666666666
[[16 12  2  0]
 [ 5 15  7  3]
 [ 3  8  9 10]
 [ 1  0 22  7]]
Fold: 2
train score:0.9888888888888889
test score:0.225
[[15  2 12  1]
 [18  6  5  1]
 [ 6 15  2  7]
 [ 0  2 24  4]]
Fold: 3
train score:0.9694444444444444
test score:0.5
[[16 11  2  1]
 [ 5 12 12  1]
 [ 8  6 10  6]
 [ 0  5  3 22]]
Fold: 4
train score:0.9613636363636363
test score:0.5
[[ 1  8  1  0]
 [ 0 10  0  0]
 [ 1  4  2  3]
 [ 0  0  3  7]]
